project:
  type: website

website:
  # title: Subodha 
  favicon: /images/subodha-logo.png
  navbar:
    # logo: images/subodha-logo.png
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - contact/index.qmd

    tools:
      - icon: whatsapp
        href: "https://wa.me/918431032239?text=I%27m+interested+to+know+more+about+Subodha."
      - icon: instagram
        href: "https://www.instagram.com/subodhacommunity"
      - icon: facebook
        href: https://facebook.com/subodhacommunity 

format:
  html:
    theme: 
      - cosmo
      - theme.scss
    css: styles.css
    toc: false



