project:
  type: website

website:
  title: "Subodha Learning Community"
  favicon: /images/subodha-logo.png
  navbar:
    background: primary
    logo: /images/subodha-navbar-logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      - cosmo
      - theme.scss
    css: styles.css
    toc: false



