project:
  type: website

website:
  title: <span style="font-family:Harrington"> Subodha </span> 
  favicon: /images/subodha-logo.png
  navbar:
    logo: images/subodha-logo.png
    background: "#d3b973"
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      - cosmo
      - theme.scss
    css: styles.css
    toc: false



